version: '2'

services:
  daemon:
    build: .
    command: "bash /go/src/github.com/goforbroke1006/dataoverseersvc/bin/run.sh"
    volumes:
      - ./:/go/src/github.com/goforbroke1006/dataoverseersvc/
  db:
    image: postgres:9.6
    ports:
      - "45433:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "12345678"
    volumes:
      - ./:/code

  redis:
    image: redis
    ports:
      - "46380:6379"